### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by MetalloloM-Edition** [MisterNorwood/Hbm-s-Nuclear-Tech-CE#674]
BEHOLD, THE GREAT LIST OF WHAT WE NEED TO PORT
## Missing:
- [x] Charging station (hbm:tile.charger) 
- [x] Refueling station (hbm:tile.refueler)
- [x] Rusty Steel Deco Block
- [x] Plushies (x3)
- [x] Steel Trapdoor
- [x] Reinforced Concrete
- [x] Rebar & Rebar Placer
- [x] Oil Spill
- [x] Fallen leaves
- [x] Boron sand & foam layers
- [x] Reeds
- [x] Glyphid Hive blocks (x3)
- [x] Glyphid Spawners (x3)
- [x] Colored Steel Scaffold (x3)
- [x] Broken toasters (x3)
- [x] Reinforced Laminate
- [x] Lantern
- [x] Spotlights (x3)
- [x] Floodlight
- [x] Tritium Lamps
- [x] Snowglobes (x5)
- [x] Bobbleheads (x22)
- [ ] Deco Light & Particle Emitters
- [x] Asbestos & Sulphur Stalagmite & Stalactite
- [x] Moonstone chunk
- [x] Compressed Biomass
- [x] Expensive items (x7)
- [x] Archineer's Wrench 
- [x] Large Fluid Container & Packaged Fluid Containers
- [x] New Blueprints 
- [x] New Blueprint Booklets
- [x] Combinator Funnel
- [x] Burner Press Preheater
- [x] Radio Isotope Cell
- [x] PT Isotope Cell
- [x] Electricity Connector
- [x] 2 Universal Fluid Ducts 
- [x] Power Detector
- [x] Paintable Coated Universal Fluid Duct
- [x] Flow Gauge Pipe
- [x] Fluid Valve & Redstone Fluid Valve
- [x] Fluid Valve with Counter
- [x] Redstone-Over-Radio anchors (x6)
- [x] Acidizer Input Partitioner
- [ ] Inserter (hbm:tile.piston_inserter)
- [ ] Custom Machine Blocks (x26)
- [ ] The Custom Machine System
- [x] Pneumatic Tube
- [x] Paintable Pneumatic Tube
- [x] Flow Control Pump
- [x] Paintable Coated Exhaust Pipe
- [x] **THE PUREX MACHINE**
- [x] **NEW ASSEMBLY MACHINE/FACTORY**
- [x] RBMK Autoloader
- [x] Naval Mine
- [x] Old Launch Pad
- [x] Dispenser Canisters 
- [x] Glyphid's Fluid Gland
- [x] Fire Extinguisher & ammo
- [x] Stick of Fishing Dynamite
- [x] Wepon Mods (x42)
- [x] Laser Pistol
- [x] Charge Thrower
- [x] Anti-Material Rifle
- [x] Cable Network Analysis Tool
- [x] Analysis Tool
- [x] Glyphid Meat
- [x] Glyphid EGG
- [x] Cloud in a Bottle
- [x] Settings Tool
- [x] New Bobmazon
- [x] Test Dummy
- [x] Undead Soldier
- [x] FBI Drone
- [x] **GLYPHIDS**
- [x] Pigeon
- [x] Plastic Bag
- [x] Parasitic Maggot
- [x] Mining Helmet
- [x] Siphon
- [x] Pipettes (x3)
- [x] New 3d geiger model
- [x] New duds
- [x] Wooden structures
- [x] World Structures
- [x] Red rooms
- [x] Broken red key
- [x] Satellite Laser Designator
- [ ] Lemegeton [Needs to be fixed]
- [x] Armor power HUD
- [x] Pedestal 
- [x] Bobcat's silo hatches
- [x] Purex JEI
- [x] Pipe anchor
- [x] **NEW FUSION REACTOR**
- [x] tile.skeleton_holder
- [ ] Railing (large & narrow)
- [x] Precision Assembly Machine (for 528 mode)
- [x] Fluorescent lamps
- [x] **FENSU/Energy Storages Rework**
- [x] Annihilator
- [ ] Redstone-over-radio keypad
- [ ] Redstone-over-radio gauge
- [ ] Rbmk display panel
- [ ] Redstone-over-radio numeric display
- [ ] Redstone-over-radio graph

## Outdated:
- [ ] Fallout layer texture
- [ ] Hemp textures
- [x] Arc welder JEI
- [x] Gas Tanks texture
- [x] Diesel Generator Model
- [ ] RT Generator model
- [x] Coated Wire Block texture
- [x] Red Copper Diode model
- [x] Industrial Mixer GUI
- [x] F.L.E.I.J.A, Blue Rinse, N2 Mine tex & models
- [x] Shrapnel Mine
- [ ] Det Cord model
- [x] Manual Override textexture
- [x] Chainsaw model
- [x] RPA model
- [x] T45 model and name (should be changed into T51)
- [x] Missile items inventory render
- [x] ~~RBMK crane console model~~ mlbv: they are pretty much the same and our version is actually (slightly) fancier; I'll keep it as-is.
- [ ] Steel wall & corner model & texture
- [x] Conveyor blocks

**Comment by MisterIceCat** [comment]
Oh Thank you ! but when all stuff was ported you can port Structures ?

**Comment by MetalloloM-Edition** [comment]
Added them to the list

**Comment by crunkazcanbe** [comment]
Can you add the Fluid Valve & Redstone Fluid Valve next please would totally go good with the mod I need the Redstone fluid valve

**Comment by MetalloloM-Edition** [comment]
They're in the list

**Comment by MisterIceCat** [comment]
Add in the list the Secret Red Key ?

**Comment by MetalloloM-Edition** [comment]
Done

**Comment by MisterIceCat** [comment]
Thank you !

**Comment by crunkazcanbe** [comment]
You forgot the RMBK auto loader

**Comment by MisterNorwood** [comment]
> You forgot the RMBK auto loader

<img width="318" height="62" alt="Image" src="https://github.com/user-attachments/assets/731f8c8b-4b1a-425f-bcae-3739d67d4fdf" />

**Comment by DiddyBlud-67-Adrian-Eeffoc** [comment]
pls update cable and deco block textures, their CTM textures dont work anyways. (ctm texture file is in game but still doesnt work)

**Comment by MisterIceCat** [comment]
Port the new model of RBMK Crane in 1.12.2 please ?

**Comment by MetalloloM-Edition** [comment]
Added to the list

**Comment by MisterIceCat** [comment]
If you want you can add Red copper cable ( Classic ) to the list ? Please

**Comment by Tiilikellari08** [comment]
Sideways scaffolds

**Comment by Tiilikellari08** [comment]
Update MRE to be same as in 1.7

**Comment by TheSlize** [comment]
what is MRE if I may know?

**Comment by Tiilikellari08** [comment]
MRE is a joke food item previously made from dirt but got updated to more relistic version in 1.7. The recipe has been updated but old description and saturation amount are still old.

**Comment by Tiilikellari08** [comment]
Update all meteor block textures

**Comment by minecrafter000001-dev** [comment]
Could ya add the paintable copper blocks? I didn’t see them yet

**Comment by TheSlize** [comment]
> Could ya add the paintable copper blocks? I didn’t see them yet

what do you mean by paintable copper blocks? if you mean paintable red copper cables, they are already in the port

**Comment by Tiilikellari08** [comment]
Chaingun turret base color

**Comment by Tiilikellari08** [comment]
Purex JEI recipes

**Comment by minecrafter000001-dev** [comment]
> > Could ya add the paintable copper blocks? I didn’t see them yet
> 
> what do you mean by paintable copper blocks? if you mean paintable red copper cables, they are already in the port

Yes that’s my bad I didn’t see them also was wondering are there gonna be He to rf converts at all?

**Comment by SilentYeti** [comment]
> > > Could ya add the paintable copper blocks? I didn’t see them yet
> > 
> > 
> > what do you mean by paintable copper blocks? if you mean paintable red copper cables, they are already in the port
> 
> Yes that’s my bad I didn’t see them also was wondering are there gonna be He to rf converts at all?

It does it seamlessly now. You don't need a HE to RF converter. It just does it automatically.

**Comment by Tiilikellari08** [comment]
Remove Turret telemetry linker block, card and controller.

**Comment by Tiilikellari08** [comment]
Update shredder power bar to 1.7 version,

**Comment by MisterIceCat** [comment]
What is going for the port of **Hbm Space 1.7.10**? I see a lot of items removed in 1.12.2 :/

**Comment by MisterNorwood** [comment]
Yeah, its going to be an addon
When? Idk, we are busy

**Comment by MisterIceCat** [comment]
Oh ok cool ! thank you and take your time

**Comment by Tiilikellari08** [comment]
Update steel wall and corner textures.

**Comment by Tiilikellari08** [comment]
Square silo hatch.

**Comment by Tiilikellari08** [comment]
Update power gauge texture

**Comment by Tiilikellari08** [comment]
Fallout powder texture

**Comment by MisterIceCat** [comment]
Update old guns added in Hbm nuclear tech mod Reload 1.12.2 please because it not work :/

**Comment by Tiilikellari08** [comment]
Remove radioisotope thermal heater

**Comment by seferlian** [comment]
> Remove radioisotope thermal heater

Some things will not be deleted. #915

**Comment by VRXDev2** [comment]
you forgot remote reactor controller.

**Comment by ArseYar** [comment]
Can you please add OC (aka OpenComputer) support, like in the original?

**Comment by TheSlize** [comment]
> Can you please add OC (aka OpenComputer) support, like in the original?

@ArseYar we already have it. If we're missing support on certain tileentities - feel free to open an issue with a list of them

**Comment by ArseYar** [comment]
> > Can you please add OC (aka OpenComputer) support, like in the original?
> 
> [@ArseYar](https://github.com/ArseYar) we already have it. If we're missing support on certain tileentities - feel free to open an issue with a list of them

@TheSlize I will drop it here; I do not want to create seperate issue. I am on version 1.1.0.0 Anyway, (for now) found list is:
- DFC receiever
- Multiblock fluid tanks

**Comment by MisterIceCat** [comment]
Hello ! I see you have been a lot of changes to the HBM Nuclear Tech Mod Community Edition, Thank you. But I wanted to know if all structures was added and if I could create a new world without any issues ?

**Comment by GuillaumeC0lin** [comment]
Hello, i saw the turret controller has been here for a while but its just a bow that shoot 2 arrows, also the airstrike designator is supposed to act like a laser designator but act as a short-range designator.
have a nice day

**Comment by MisterIceCat** [comment]
The list are not updated sorry

**Comment by Zuphrus** [comment]
New battery system and FENSU

**Comment by MisterIceCat** [comment]
What ?

**Comment by nuhyuh** [comment]
bobert heavily reworked energy storage so it needs to be ported

**Comment by MisterIceCat** [comment]
Ah ok I think it was not reworked since 10 years maybe ?

**Comment by Zuphrus** [comment]
The new FENSU is all i REALLY ask for lmfao

**Comment by Zuphrus** [comment]
INFINITE ENERGY STORAGE? WHO CAN'T PASS THAT UP

**Comment by Vidarin** [comment]
Broken red key has been done for a while now

**Comment by ricardojoseurribarri-wq** [comment]
Please, the fluid barrels don't say what they contain in Spanish.

**Comment by moddingforreal2** [comment]
Could you add the redstone-over-radio keypad, redstone-over-radio gauge, rbmk display panel, redstone-over-radio numeric display, redstone-over-radio graph to the to-do list?

**Comment by NoPressF** [comment]
> Could you add the redstone-over-radio keypad, redstone-over-radio gauge, rbmk display panel, redstone-over-radio numeric display, redstone-over-radio graph to the to-do list?

Yes

**Comment by oniterraria** [comment]
could you add can of mug root beer?

**Comment by Shibva** [comment]
it appears the Folly parts are missing from the redroom lootpool
